### ISSUE TITLE
libglib 2.0 fails to compile with gcc 6.2.1

### ISSUE THREAD

**Issue by awegrzyn** [alisw/alibuild#423]
[log.txt](https://github.com/alisw/alibuild/files/789476/log.txt)
According to bug tracker it should work with rev 15017.
I proceed with compilation after installing autotools by yum.

**Comment by dberzano** [comment]
Rev 15017 of what package? I see `glib` is part of `pkg-config`.

**Comment by awegrzyn** [comment]
I don't remember what package I was thinking about...
The error that causes the compilation to fail comes indeed from pkg-config:
```
  CC       libglib_2_0_la-gdate.lo
gdate.c: In function 'g_date_strftime':
gdate.c:2497:7: error: format not a string literal, format string not checked [-Werror=format-nonliteral]
       tmplen = strftime (tmpbuf, tmpbufsize, locale_format, &tm);
       ^~~~~~
cc1: some warnings being treated as errors
Makefile:1386: recipe for target 'libglib_2_0_la-gdate.lo' failed
```

**Comment by dberzano** [comment]
Sure, don't worry, it's fixed in any case (not yet upstream).

**Comment by fedelibre** [comment]
I happened to find this issue while building a package which uses an old version of glib. [This commit](https://github.com/GNOME/glib/commit/0817af40e8c74c721c30f6ef482b1f53d12044c7#diff-4fecd8bf544b0cb6678ecd9a2f4f3d69) helped me to fix the error and go on.

**Comment by fedelibre** [comment]
see also [this commit](https://github.com/GNOME/glib/commit/8cdbc7fb2c8c876902e457abe46ee18a0b134486)
